_target_: src.models.timm_module.TimmLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# criterion:
#   _target: torch.nn.Sigmoid
#   _partial_: true

net:
  _target_: timm.create_model
  model_name: densenet121
  pretrained: True
  num_classes: 5
