_target_: src.datamodules.chexpert_datamodule.CheXpertDataModule
data_dir: ${paths.data_dir}
batch_size: 128
# train_val_test_split: [55_000, 5_000, 10_000]
num_workers: 16
pin_memory: False
image_root_path: "CheXpert-v1.0-pad224/"
image_size: 224